# .github/workflows/release.yml
on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/common.yml

  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - run: gh release create $(git rev-parse --short HEAD) --generate-notes

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: echo "Deploying..."