on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/common.yml

  release:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: gh release create $(git rev-parse --short HEAD) --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: echo "Deploying..."